name: Build and Push to AWS ECR

on:
  push:
    branches: [master]

env:
  AWS_REGION: us-east-1                # ← Update to your region
  IMAGE_NAME: estore
  IMAGE_VERSION: 1.0.${{ github.run_number }}
  ECR_REPOSITORY: estore               # ← Must already exist in ECR

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          IMAGE_URI=${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_VERSION}
          LATEST_URI=${ECR_REGISTRY}/${ECR_REPOSITORY}:latest

          docker build -t $IMAGE_URI .
          docker tag $IMAGE_URI $LATEST_URI

          docker push $IMAGE_URI
          docker push $LATEST_URI

      - name: Output image URI
        run: |
          echo "Image pushed: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_VERSION }}"
